name: issues workflow
on: issues
jobs:
    output-info:
        name: output details
        runs-on: ubuntu-latest

        steps:
         - name: output event log
           run: echo "${{github.event}}"
