name: issues workflow
on: issue_comment
jobs:
    output-info:
        name: output details
        runs-on: ubuntu-latest

        steps:
         - name: output event log
           run: echo "${{ toJson(github.event) }}"
